Repository OlgaCybulska/movies-browser, pull requests merged in 2024-04, with the labels that each got.

#18 logic/movie-details-based-on-api
  src/app/GlobalStyle.js
  src/app/theme.js
  src/common/GridWrapper/styled.js
  src/common/Rating/styled.js
  src/common/Section/index.js
  src/common/Tile/index.js
  src/common/Tile/styled.js
  src/features/SiteHeader/NavBar/index.js
  src/features/SiteHeader/NavBar/styled.js
  src/features/SiteHeader/SearchBar/styled.js
  src/features/SiteHeader/index.js
  src/features/SiteHeader/styled.js
  src/features/movies/MovieDetails/Backdrop/index.js
  src/features/movies/MovieDetails/index.js
  src/features/movies/MovieDetails/styled.js
  src/features/movies/MovieList/index.js
  src/features/movies/MovieList/styled.js
  src/utils/API/apiDataURLs.js
  src/utils/API/dataSlice.js
  src/utils/dataFormatFunctions.js
Labels: enhancement

#21 Features/people list and people details
  src/common/Tile/index.js
  src/features/movies/MovieDetails/index.js
  src/features/movies/MovieList/index.js
  src/features/people/PeopleDetails/index.js
  src/features/people/PeopleList/index.js
  src/utils/API/apiDataURLs.js
  src/utils/API/dataSlice.js
Labels: enhancement

#22 documentation/readme-update
  README.md
  readme_authors.png
  readme_header.png
  readme_mainPageScreenshot.png
Labels: documentation

#24 features/metatags index html
  public/icon.png
  public/index.html
  public/share.png
Labels: enhancement

#26 Features/minor bug fixes
  src/common/Tile/index.js
  src/features/movies/MovieDetails/index.js
  src/features/movies/MovieList/index.js
  src/features/people/PeopleDetails/index.js
  src/features/people/PeopleList/index.js
Labels: bug

#27 Features/error-page-clickable-button
  src/common/ErrorPage/index.js
  src/common/ErrorPage/styled.js
Labels: enhancement

#31 Logic/search bar input reset
  src/features/SiteHeader/SearchBar/index.js
  src/utils/queryParams.js
Labels: enhancement

#30 Features/fix rating and genres look
  src/common/Rating/index.js
  src/common/Rating/styled.js
  src/common/Tile/index.js
  src/common/Tile/styled.js
  src/features/movies/MovieDetails/index.js
  src/utils/API/dataSaga.js
Labels: enhancement
